// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../src/Groth16Verifier.sol";  // auto-generated by snarkjs
import "../src/VerisOracleV2.sol";

/**
 * Deploy Groth16Verifier + VerisOracleV2
 *
 * Run AFTER: bash circuits/setup.sh
 * (which generates src/Groth16Verifier.sol)
 *
 * forge script script/DeployVerifier.s.sol \
 *   --rpc-url https://bsc-testnet-rpc.publicnode.com \
 *   --private-key $PRIVATE_KEY \
 *   --broadcast
 */
contract DeployVerifier is Script {

    function run() external {
        uint256 privateKey = vm.envUint("PRIVATE_KEY");
        address submitter  = vm.addr(privateKey);

        vm.startBroadcast(privateKey);

        // 1. Deploy Groth16Verifier (generated by snarkjs)
        Groth16Verifier verifier = new Groth16Verifier();
        console.log("Groth16Verifier:", address(verifier));

        // 2. Deploy VerisOracleV2 pointing to the verifier
        VerisOracleV2 oracleV2 = new VerisOracleV2(submitter, address(verifier));
        console.log("VerisOracleV2: ", address(oracleV2));

        vm.stopBroadcast();

        console.log("\n=== ADD TO .env ===");
        console.log("GROTH16_VERIFIER=", address(verifier));
        console.log("VERIS_ORACLE_V2= ", address(oracleV2));

        console.log("\nTest with:");
        console.log("  node oracle-agent-zk.js");
    }
}
